### ISSUE TITLE
[1.7] Memory leak with explosions

### ISSUE THREAD

**Issue by kmecpp** [BuiltBrokenModding/ICBM-Classic#160]
Not sure how to replicate the issue but my server ran out of memory. Analyzing the heap dump with VisualVM shows this

![image](https://user-images.githubusercontent.com/6520738/44624602-7bdbf500-a8c0-11e8-990a-55b3dfd2cfa5.png)

```
"Thread-1893" prio=1 tid=3601 BLOCKED
    at com.builtbroken.mc.imp.transform.vector.Location.newPos(Location.java:79)
    at com.builtbroken.mc.imp.transform.vector.Location.newPos(Location.java:22)
    at com.builtbroken.jlib.data.vector.Pos3D.add(Pos3D.java:36)
    at com.builtbroken.jlib.data.vector.Pos3D.sub(Pos3D.java:53)
    at com.builtbroken.jlib.data.vector.Pos3D.sub(Pos3D.java:63)
    at com.builtbroken.jlib.data.vector.Pos3D.distance(Pos3D.java:84)
    at icbm.classic.content.explosive.thread.ThreadLargeExplosion.run(ThreadLargeExplosion.java:80)
       local variable: com.builtbroken.mc.imp.transform.vector.Location#3900

  
"Thread-1894" prio=1 tid=3602 RUNNABLE
    at java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:48)
    at java.util.Arrays.copyOf(Arrays.java:3181)
    at java.util.ArrayList.grow(ArrayList.java:265)
    at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
    at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
    at java.util.ArrayList.add(ArrayList.java:462)
       local variable: java.util.ArrayList#97
       local variable: com.builtbroken.mc.imp.transform.vector.Pos#6769696
    at icbm.classic.content.explosive.thread.ThreadLargeExplosion.run(ThreadLargeExplosion.java:95)
       local variable: com.builtbroken.mc.imp.transform.vector.Location#13

  
"Thread-1895" prio=1 tid=3603 BLOCKED
    at com.builtbroken.mc.imp.transform.vector.AbstractLocation.toPos(AbstractLocation.java:177)
    at icbm.classic.content.explosive.thread.ThreadLargeExplosion.run(ThreadLargeExplosion.java:95)
       local variable: com.builtbroken.mc.imp.transform.vector.Location#3670

```

**Comment by DarkGuardsman** [comment]
Did you set the explosive size really high?

**Comment by kmecpp** [comment]
Have destroy_unbreakable_blocks=false. Everything else is default

Antimatter blast_radius=55

There is no "explosive-size" config. Using 1.7.10

**Comment by DarkGuardsman** [comment]
Can you give me a full rundown of what mods your server has? Including launch settings such as garbage collection, etc.  As well what was going on at the time of the issue. As this normally shouldn't happen as the GC should collect dead objects quickly. You have almost 100M objects when normal explosions should max at 1M for anti-matter. Even then it should dump most of its data mid-run.

**Comment by kmecpp** [comment]
I can temporarily upload the heap dump as well if necessary, but I'm not really sure what was going on at the time of the issue. If it happens again I can probably get more information.

**Launch Settings:**
-Xms{START_MEMORY}M
-Xmx{MAX_MEMORY}M
-XX:+UseConcMarkSweepGC
-XX:+AggressiveOpts
-XX:+HeapDumpOnOutOfMemoryError
-XX:HeapDumpPath=DUMP.hprof
-Djava.io.tmpdir=tmp
-Djline.terminal=jline.UnsupportedTerminal

**Mods:** (I'm aware it's cut off. WorldEdit is the last one)
![image](https://user-images.githubusercontent.com/6520738/44694767-7f48bb00-aa3d-11e8-94c5-58e0b056fa27.png)
![image](https://user-images.githubusercontent.com/6520738/44694763-7a840700-aa3d-11e8-968d-82c346292f7f.png)

**Plugins:**
![image](https://user-images.githubusercontent.com/6520738/44694731-40b30080-aa3d-11e8-952c-7c888d5c0366.png)

**Comment by GHXX** [comment]
Closing all 1.7.10 issues since we are no longer supporting it officially and its unlikely that it receives any patches.
