### ISSUE TITLE
Disabling Items in config causes a crash

### ISSUE THREAD

**Issue by simplysimon0** [BuiltBrokenModding/ICBM-Classic#218]
Any time I try to disable any of the items i get a crash from the game trying make item models for the disabled items. 

Here is the bit from my log:
java.lang.NullPointerException
    at icbm.classic.client.ClientProxy.newItemModel(ClientProxy.java:259)
    at icbm.classic.client.ClientProxy.doLoadModels(ClientProxy.java:106)
    at icbm.classic.ICBMClassic.registerAllModels(ICBMClassic.java:347)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_615_ICBMClassic_registerAllModels_ModelRegistryEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.client.FMLClientHandler.fireSidedRegistryEvents(FMLClientHandler.java:1062)
    at net.minecraftforge.fml.common.FMLCommonHandler.fireSidedRegistryEvents(FMLCommonHandler.java:764)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by LemADEC** [comment]
As of "1.12.2-3.3.0b65-UNSTABLE build 65", issue is reproduced by disabling just the Battery, while Circuits, Ingots, Plates and Wires can be disabled safely.
