### ISSUE TITLE
Exception on server shutdown

### ISSUE THREAD

**Issue by Tommeh1** [BuiltBrokenModding/ICBM-Classic#224]
[latest.log](https://github.com/BuiltBrokenModding/ICBM-Classic/files/3298631/latest.log)
Same log on pastebin: https://pastebin.com/vwBkjdyr
After a restart this warning showed up, idk if this is in any way related.
[20:07:48] [Server thread/WARN] [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.EntityLivingBase from class icbm.classic.prefab.entity.EntityBase

**Comment by DarkGuardsman** [comment]
I'm not seeing that in the log

What I do see is this
```
net.minecraftforge.event.world.WorldEvent$Unload@2a00e2aa:
java.util.ConcurrentModificationException: null
    at java.util.HashMap$HashIterator.remove(HashMap.java:1451) ~[?:1.8.0_111]
    at java.util.Collection.removeIf(Collection.java:415) ~[?:1.8.0_111]
    at net.minecraftforge.common.util.FakePlayerFactory.unloadWorld(FakePlayerFactory.java:70) ~[FakePlayerFactory.class:?]
    at net.minecraftforge.common.ForgeInternalHandler.onDimensionUnload(ForgeInternalHandler.java:84) ~[ForgeInternalHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_91_ForgeInternalHandler_onDimensionUnload_Unload.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
    at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:452) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$4.run(MinecraftServer.java:1579) [MinecraftServer$4.class:?]
```

**Comment by Tommeh1** [comment]
At line 753 you can see the server stopping after which you see that which i believe to be caused by ICBM.
I am not sure though but it is my best bet

**Comment by GHXX** [comment]
Just going through the issues right now, and it appears that the line [Server thread/WARN] [minecraft/EntityDataManager]: defineId called for: class... isnt even in the log you posted.
To me this looks like a forge issue rather than an icbm issue, but what do you think, @DarkGuardsman ?
I am assuming you, @CraftalotReloaded , are worried about the log line saying "[icbmclassic]: Stopping threads". This is just a log line that mentions that icbm is stopping some of its own threads since the server is shutting down.
