### ISSUE TITLE
BlastGasBase NoSuchMethodError

### ISSUE THREAD

**Issue by clienthax** [BuiltBrokenModding/ICBM-Classic#250]
blast-rewrite branch
Debilitation nuke

```
Description: Ticking entity

java.lang.NoSuchMethodError: net/minecraft/util/math/BlockPos$MutableBlockPos.func_189535_a(Lnet/minecraft/entity/Entity;)Lnet/minecraft/util/math/BlockPos$MutableBlockPos; (loaded from jar:file:/home/container/minecraft_server.1.12.2.jar!/et$a.class by net.minecraft.launchwrapper.LaunchClassLoader@1c9769cd) called from class icbm.classic.content.blast.BlastGasBase (loaded from jar:file:/home/container/./mods/ICBM-classic-1.12.2-4.0.0b20191030225013.jar!/icbm/classic/content/blast/BlastGasBase.class by net.minecraft.launchwrapper.LaunchClassLoader@1c9769cd).
    at icbm.classic.content.blast.BlastGasBase.canGasEffect(BlastGasBase.java:217)
    at icbm.classic.content.blast.BlastGasBase$$Lambda$5883.00000000C1A70230.apply(Unknown Source)
    at net.minecraft.world.chunk.Chunk.getEntitiesOfTypeWithinAABB(Chunk.java:936)
    at net.minecraft.world.WorldServer.getEntitiesWithinAABB(WorldServer.java:4796)
    at icbm.classic.content.blast.BlastGasBase.doExplode(BlastGasBase.java:126)
    at icbm.classic.content.blast.Blast.onBlastTick(Blast.java:160)
    at icbm.classic.content.entity.EntityExplosion.onUpdate(EntityExplosion.java:138)
    at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:167)
    at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zmb000(WorldServer.java:4740)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:3930)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:813)```

**Comment by clienthax** [comment]
Seems for some reason MutableBlockPos.setPos(Entity) is marked a Client only in mc..
https://github.com/T145/allthecreepers/issues/13
