### ISSUE TITLE
getBlockState is called on unloaded chunks, causing off thread generation/chunkload

### ISSUE THREAD

**Issue by clienthax** [BuiltBrokenModding/ICBM-Classic#251]
branch: blast-rewrite

```
> [14:46:19] [ThreadExplosion-29/ERROR] [icbmclassic]: ThreadExplosion#run() -> Unexpected error
java.lang.IllegalStateException: CauseStackManager called from off main thread (current='ThreadSmallExplosion{class=class icbm.classic.content.blast.thread.ThreadSmallExplosion, name=ThreadExplosion-29, priority=1, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:121) ~[SpongeCauseStackManager.class:1.12.2-2838-7.1.7-RC3928]
at org.spongepowered.common.event.SpongeCauseStackManager.pushCauseFrame(SpongeCauseStackManager.java:240) ~[SpongeCauseStackManager.class:1.12.2-2838-7.1.7-RC3928]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.redirect$impl$createEntityFromCompound$zmj000(AnvilChunkLoader.java:1895) ~[aye.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.readChunkEntity(AnvilChunkLoader.java:529) ~[aye.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) ~[aye.class:?]
at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) ~[ChunkIOProvider.class:?]
at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89) ~[on.class:?]
at net.minecraft.world.gen.ChunkProviderServer.redirect$impl$ProvideChunkForced$zml000(ChunkProviderServer.java:1658) ~[on.class:?]
at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135) ~[on.class:?]
at net.minecraft.world.World.getChunk(World.java:310) ~[amu.class:?]
at net.minecraft.world.World.getChunk(World.java:305) ~[amu.class:?]
at net.minecraft.world.WorldServer.getBlockState(WorldServer.java:5064) ~[oo.class:?]
at icbm.classic.content.blast.thread.ThreadSmallExplosion.doRun(ThreadSmallExplosion.java:54) ~[ThreadSmallExplosion.class:1.12.2-4.0.0b20191030225013]
at icbm.classic.content.blast.thread.ThreadExplosion.run(ThreadExplosion.java:71) [ThreadExplosion.class:1.12.2-4.0.0b20191030225013]
```

DarkCow said this is likely due to the change from Pos -> BlockPos, where Pos had internal chunk loaded checks.

**Comment by bl4ckscor3** [comment]
Opted for the non-loading fix for now.

**Comment by clienthax** [comment]
Seems this is also an issue on antimatter
