### ISSUE TITLE
Redmatter crash

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#29]
As of ICBM-classic-1.7.10-2.15.1b37-universal, when exploding 2 redmatter in sequence in SSP, game crashed:
```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 2/15/17 10:53 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at icbm.classic.content.explosive.blast.BlastRedmatter.doDestroyBlocks(BlastRedmatter.java:114)
	at icbm.classic.content.explosive.blast.BlastRedmatter.doExplode(BlastRedmatter.java:80)
	at icbm.classic.content.explosive.blast.Blast.onExplode(Blast.java:77)
	at icbm.classic.content.entity.EntityExplosion.func_70071_h_(EntityExplosion.java:124)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at icbm.classic.content.explosive.blast.BlastRedmatter.doDestroyBlocks(BlastRedmatter.java:114)
	at icbm.classic.content.explosive.blast.BlastRedmatter.doExplode(BlastRedmatter.java:80)
	at icbm.classic.content.explosive.blast.Blast.onExplode(Blast.java:77)
	at icbm.classic.content.entity.EntityExplosion.func_70071_h_(EntityExplosion.java:124)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Entity being ticked --
Details:
	Entity Type: icbmclassic.ICBMProceduralExplosion (icbm.classic.content.entity.EntityExplosion)
	Entity ID: 311049
	Entity Name: Explosion
	Entity's Exact location: -105.93, 91.19, 358.05
	Entity's Block location: World: (-106,91,358), Chunk: (at 6,5,6 in -7,22; contains blocks -112,0,352 to -97,255,367), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 6.34, -0.44, 7.29
Stacktrace:
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['LemADEC'/3175, l='New World', x=-182.47, y=65.98, z=204.24]]
	Chunk stats: ServerChunkCache: 301 Drop: 0
	Level seed: -7316155146680488053
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-212,64,252), Chunk: (at 12,4,12 in -14,15; contains blocks -224,0,240 to -209,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 63332 game time, 63332 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 91071 (now: false), thunder time: 72898 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 296806280 bytes (283 MB) / 1812463616 bytes (1728 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 94 mods loaded, 94 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UCHIJAAAA	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	WarpDriveCore{1.7.10-1.3.30.-} [WarpDriveCore] (minecraft.jar) 
	UCHIJAAAA	mcdiscord{2.0.0} [MC Discord] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJAAAA	ae2stuff{0.5.1.61} [AE2 Stuff] (ae2stuff-0.5.1.61-mc1.7.10.jar) 
	UCHIJAAAA	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar) 
	UCHIJAAAA	nevermine{2.3} [AdventOfAscension] (AoA-2.4.B.jar) 
	UCHIJAAAA	AppleCore{1.3.8} [AppleCore] (AppleCore-mc1.7.10-1.3.8.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.5-115.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.4-247.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.347} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8_dev_r8} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8_dev_r8 - MC 1.7.10.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAA	MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.7.10-3.0.13.jar) 
	UCHIJAAAA	CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
	UCHIJAAAA	CustomOreGen{1.2.26} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.26.jar) 
	UCHIJAAAA	Mekanism{9.0.3} [Mekanism] (Mekanism-1.7.10-9.0.3.277.jar) 
	UCHIJAAAA	DefenseTech{1.0.1} [DefenseTech] (DefenseTech-1.7.10-1.0.1.46-Lem1.jar) 
	UCHIJAAAA	Ding{MC1.7.10v2} [Ding] (Ding-MC1.7.10v2.jar) 
	UCHIJAAAA	dsurround{1.0.5.9} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.5.9.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAAAA	evilcraft{0.9.12} [EvilCraft] (EvilCraft-1.7.10-0.9.12.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar) 
	UCHIJAAAA	GunCus{1.7.10-3.47.0.-} [Gun Customization] (GunCustomization-1.7.10-3.47.0.-.jar) 
	UCHIJAAAA	VoltzEngine{0.27.4.345} [Voltz Engine] (VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar) 
	UCHIJAAAA	icbmclassic{2.15.1.37} [ICBM-Classic] (ICBM-classic-1.7.10-2.15.1b37-universal.jar) 
	UCHIJAAAA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UCHIJAAAA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] (Lucky_Block_v5-1-0.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	MekanismGenerators{9.0.3} [MekanismGenerators] (MekanismGenerators-1.7.10-9.0.3.277.jar) 
	UCHIJAAAA	MekanismTools{9.0.3} [MekanismTools] (MekanismTools-1.7.10-9.0.3.277.jar) 
	UCHIJAAAA	numina{0.4.1.104} [Numina] (Numina-0.4.1.104.jar) 
	UCHIJAAAA	powersuits{@VERSION@} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.1.109.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UCHIJAAAA	openmodularturrets{2.2.10-233} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.2.10-233.jar) 
	UCHIJAAAA	PneumaticCraft{1.12.7-150} [PneumaticCraft] (PneumaticCraft-1.7.10-1.12.7-150-universal.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.2-92.jar) 
	UCHIJAAAA	ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.7.10-1.3.jar) 
	UCHIJAAAA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.10.8} [Storage Drawers] (StorageDrawers-1.7.10-1.10.8.jar) 
	UCHIJAAAA	TextureGeneratorLib{0.2} [TextureGeneratorLib] (TextureGeneratorLib-1.7.10_vBeta2.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.0-171.jar) 
	UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJAAAA	UndergroundBiomes{0.6h} [Underground Biomes Constructs] (undergroundBiomes-1.7.10-0.8-gyro-exp-1.11-Lem.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	WarpDrive{1.7.10-1.3.30.-} [WarpDrive] (WarpDrive-1.7.10-1.3.30.-.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	UCHIJAAAA	WTFCore{1.7} [WhiskyTangoFox's Core] (WTFCore-1.7.10_v1.7.jar) 
	UCHIJAAAA	CaveBiomes{1.6} [WhiskyTangoFox's CaveBiomes] (WTFCaveBiomes-1.7.10_v1.6.jar) 
	UCHIJAAAA	WTFTweaks{1.40} [WhiskyTangoFox's Tweaks] (WTFTweaks-1.7.10_v1.4.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.347} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.347} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJAAAA	HungerOverhaul{1.7.10-1.0.0.jenkins104} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jenkins104.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.1.3-327
	ThermalFoundation: -[1.7.10]1.2.5-115
	ThermalExpansion: -[1.7.10]4.1.4-247
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.2-92
	ThermalDynamics: -[1.7.10]1.2.0-171
	List of loaded APIs: 
		* AgriCraftAPI (1.0) from AgriCraft-1.7.10-1.5.0.jar
		* AppleCoreAPI (1.2.0) from AppleCore-mc1.7.10-1.3.8.jar
		* appliedenergistics2|API (rv3) from appliedenergistics2-rv3-beta-6.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* BotaniaAPI (76) from Botania r1.8-249.jar
		* BuildCraftAPI|core (1.0) from extrautilities-1.2.12.jar
		* BuildCraftAPI|tools (1.0) from extrautilities-1.2.12.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.8_dev_r8 - MC 1.7.10.jar
		* ChiselAPI (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Carving (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.5.11.jar
		* CoFHAPI (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|block (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHAPI|core (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHAPI|energy (1.7.10R1.0.10) from Mekanism-1.7.10-9.0.3.277.jar
		* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|inventory (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHAPI|item (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHAPI|tileentity (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHAPI|transport (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|world (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|audio (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHLib|gui|container (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|element (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHLib|inventory (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|render (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHLib|render|particle (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHLib|util (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHLib|util|helpers (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHLib|util|position (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.2-182.jar
		* CoFHLib|world (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|world|feature (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* ComputerCraft|API (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|FileSystem (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Lua (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Media (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Peripheral (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Permissions (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Redstone (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Turtle (1.75) from ComputerCraft1.75.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* IC2API (1.0) from industrialcraft-2-2.2.827-experimental.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.7.7.jar
		* inpure|api (1.7) from INpureCore-[1.7.10]1.0.0B9-62.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
		* MekanismAPI|reactor (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
		* MekanismAPI|recipe (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
		* OpenBlocks|API (1.1) from OpenBlocks-1.7.10-1.5.1.jar
		* PneumaticCraftApi (1.0) from PneumaticCraft-1.7.10-1.12.7-150-universal.jar
		* RailcraftAPI|crafting (1.0.0) from ImmersiveEngineering-0.7.7.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* Thaumcraft|API (4.2.2.0) from Pam's HarvestCraft 1.7.10Lb.jar
		* VoltzEngineAPI (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|crafting-items (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|data (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|energy (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|energy-items (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|event (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|explosive-items (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|explosives (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|items (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|recipe (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|tile (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|tools (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|weapons (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.10 from Mekanism-1.7.10-9.0.3.277.jar).
                    It is a supported version, but that difference may lead to problems.
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:ON
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['LemADEC'/3175, l='New World', x=-182.47, y=65.98, z=204.24]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by DarkGuardsman** [comment]
Forgot I coded my pos system to return null if its in an unloaded chunk.
