### ISSUE TITLE
[1.12] Serverside concurrent modification exception

### ISSUE THREAD

**Issue by Joey-Destroyah** [BuiltBrokenModding/ICBM-Classic#295]
java.util.ConcurrentModificationException
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 3/29/20 5:23 PM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at icbm.classic.lib.radar.RadarMap.collectEntitiesInChunk(RadarMap.java:228)
	at icbm.classic.content.entity.missile.MissileEventHandler.chunkUnload(MissileEventHandler.java:43)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_MissileEventHandler_chunkUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:879)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:269)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at icbm.classic.lib.radar.RadarMap.collectEntitiesInChunk(RadarMap.java:228)
	at icbm.classic.content.entity.missile.MissileEventHandler.chunkUnload(MissileEventHandler.java:43)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_MissileEventHandler_chunkUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:879)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:269)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Joseph_da_IT_Guy'/2525, l='New World', x=53.61, y=79.24, z=208.05]]
	Chunk stats: ServerChunkCache: 449 Drop: 9
	Level seed: -1797220104376273678
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (208,64,256), Chunk: (at 0,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 23524 game time, 2287 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 55174 (now: false), thunder time: 32987 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 575642104 bytes (548 MB) / 1241513984 bytes (1184 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID          | Version                     | Source                                       | Signature                                |
	|:------ |:----------- |:--------------------------- |:-------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft   | 1.12.2                      | minecraft.jar                                | None                                     |
	| LCHIJA | mcp         | 9.42                        | minecraft.jar                                | None                                     |
	| LCHIJA | FML         | 8.0.99.99                   | forge-1.12.2-14.23.5.2838.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge       | 14.23.5.2838                | forge-1.12.2-14.23.5.2838.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | icbmclassic | 1.12.2-4.0.1.20200328215453 | ICBM-classic-1.12.2-4.0.1b20200328215453.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Joseph_da_IT_Guy'/2525, l='New World', x=53.61, y=79.24, z=208.05]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Joey-Destroyah** [comment]
Also, i always get kicked off of my missiles when i try to launch them, while im riding on them.

**Comment by Tommeh1** [comment]
Can verify using custom build until this commit https://github.com/BuiltBrokenModding/ICBM-Classic/commit/a5d481c486a74b288a0cf4ccf4a12cd963644fce
I am however unable to find a solid way of reproducing it.
It may also be worth to note that the 'Firing missile at PosD3' message appeared twice after right clicking once with the laser designator right before this crash.

**Comment by GHXX** [comment]
Is there any particular reason for closing this?

**Comment by Joey-Destroyah** [comment]
¯\_(ツ)_/¯
Don't Remember :P

**Comment by GHXX** [comment]
lets keep this open, please.
