### ISSUE TITLE
Bugs with laser-point launch

### ISSUE THREAD

**Issue by Harchvertelol** [BuiltBrokenModding/ICBM-Classic#311]
By the way, I found a bug: on the mod version "ICBM-classic-1.12.2-4.0.1b20200328215453", when launching with the laser pointer, the rocket after the strike remains on the launcher, the launchpad says that it is ready to launch, but launching is not possible, only dismantling the launcher helps.

Else unknown for me bugs, console logs:

[02:20:19] [Server thread/ERROR] [FML]: An Entity type icbm.classic.content.entity.EntityExplosion has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1772) ~[vg.class:?]
at net.minecraft.entity.Entity.func_70039_c(Entity.java:1654) ~[vg.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:362) [aye.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:174) [aye.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
at icbm.classic.content.blast.Blast.save(Blast.java:429) ~[Blast.class:1.12.2-4.0.1b20200328215453]
at icbm.classic.content.entity.EntityExplosion.func_70014_b(EntityExplosion.java:206) ~[EntityExplosion.class:1.12.2-4.0.1b20200328215453]
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1743) ~[vg.class:?]
... 10 more
[02:20:57] [Server thread/ERROR] [FML]: An Entity type icbm.classic.content.entity.EntityExplosion has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1772) ~[vg.class:?]
at net.minecraft.entity.Entity.func_70039_c(Entity.java:1654) ~[vg.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:362) [aye.class:?]
at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
at org.dynmap.forge.ForgeMapChunkCache.getLoadedChunks(ForgeMapChunkCache.java:1352) [ForgeMapChunkCache.class:?]
at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:772) [DynmapPlugin$ForgeServer$1.class:?]
at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:767) [DynmapPlugin$ForgeServer$1.class:?]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
at org.dynmap.forge.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:859) [DynmapPlugin$ForgeServer.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_265_ForgeServer_tickEvent_ServerTickEvent.invoke(.dynamic) [?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
at icbm.classic.content.blast.Blast.save(Blast.java:429) ~[Blast.class:1.12.2-4.0.1b20200328215453]
at icbm.classic.content.entity.EntityExplosion.func_70014_b(EntityExplosion.java:206) ~[EntityExplosion.class:1.12.2-4.0.1b20200328215453]
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1743) ~[vg.class:?]
... 17 more
[02:21:49] [Server thread/ERROR] [FML]: An Entity type icbm.classic.content.entity.EntityExplosion has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1772) ~[vg.class:?]
at net.minecraft.entity.Entity.func_70039_c(Entity.java:1654) ~[vg.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:362) [aye.class:?]
at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
at org.dynmap.forge.ForgeMapChunkCache.getLoadedChunks(ForgeMapChunkCache.java:1352) [ForgeMapChunkCache.class:?]
at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:772) [DynmapPlugin$ForgeServer$1.class:?]
at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:767) [DynmapPlugin$ForgeServer$1.class:?]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
at org.dynmap.forge.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:859) [DynmapPlugin$ForgeServer.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_265_ForgeServer_tickEvent_ServerTickEvent.invoke(.dynamic) [?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
at icbm.classic.content.blast.Blast.save(Blast.java:429) ~[Blast.class:1.12.2-4.0.1b20200328215453]
at icbm.classic.content.entity.EntityExplosion.func_70014_b(EntityExplosion.java:206) ~[EntityExplosion.class:1.12.2-4.0.1b20200328215453]
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1743) ~[vg.class:?]
... 17 more
[02:22:31] [Server thread/ERROR] [FML]: An Entity type icbm.classic.content.entity.EntityExplosion has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1772) ~[vg.class:?]
at net.minecraft.entity.Entity.func_70039_c(Entity.java:1654) ~[vg.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:362) [aye.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:174) [aye.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:271) [on.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
at icbm.classic.content.blast.Blast.save(Blast.java:429) ~[Blast.class:1.12.2-4.0.1b20200328215453]
at icbm.classic.content.entity.EntityExplosion.func_70014_b(EntityExplosion.java:206) ~[EntityExplosion.class:1.12.2-4.0.1b20200328215453]
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1743) ~[vg.class:?]
... 11 more
[02:22:34] [Server thread/ERROR] [FML]: An Entity type icbm.classic.content.entity.EntityExplosion has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1772) ~[vg.class:?]
at net.minecraft.entity.Entity.func_70039_c(Entity.java:1654) ~[vg.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:362) [aye.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:174) [aye.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
at icbm.classic.content.blast.Blast.save(Blast.java:429) ~[Blast.class:1.12.2-4.0.1b20200328215453]
at icbm.classic.content.entity.EntityExplosion.func_70014_b(EntityExplosion.java:206) ~[EntityExplosion.class:1.12.2-4.0.1b20200328215453]
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1743) ~[vg.class:?]
... 10 more
[02:22:34] [Server thread/ERROR] [FML]: An Entity type icbm.classic.content.entity.EntityExplosion has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1772) ~[vg.class:?]
at net.minecraft.entity.Entity.func_70039_c(Entity.java:1654) ~[vg.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:362) [aye.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:174) [aye.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:271) [on.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
at icbm.classic.content.blast.Blast.save(Blast.java:429) ~[Blast.class:1.12.2-4.0.1b20200328215453]
at icbm.classic.content.entity.EntityExplosion.func_70014_b(EntityExplosion.java:206) ~[EntityExplosion.class:1.12.2-4.0.1b20200328215453]
at net.minecraft.entity.Entity.func_189511_e(Entity.java:1743) ~[vg.class:?]
... 11 more

**Comment by GHXX** [comment]
This may be related to #299 , just writing this down for later

**Comment by GHXX** [comment]
This may have been fixed in commit 9c6db8e
(stacktrace is very similar to #346)
