### ISSUE TITLE
ICBM Mod doesn't work correct on forge server

### ISSUE THREAD

**Issue by micha12342** [BuiltBrokenModding/ICBM-Classic#378]
We have installed a forge server in version 1.12.2 - 14.23.5.2859. We installed the same Forge version on the client. We have installed the ICBM Classic Mod on the client and on the server in the "Mod" directory. The items of the mod are shown to us, but we cannot place the blocks, they do not stay where we want to place them. Maybe we're not using the mods or the server properly. Many thanks in advance for hints.

**Comment by bl4ckscor3** [comment]
The mod needs to be in the `mods` folder of your server, and you need to start the server using the `forge-1.12.2-14.23.5.2859.jar` file. If you start the server using `minecraft_server.1.12.2.jar`, then you will only have a vanilla server.

**Comment by micha12342** [comment]
Hi bl4ackscor3, thats what we have tried. But if we start the forge-server e.g. java -jar forge-1.12.2-14.23.5.2859.jar we got only the following error message:

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

If we ask about this error on the mainpage of forge we only get the message, that this is not the latest version and its not supported.

**Comment by bl4ckscor3** [comment]
You need to use Java 8 to run the server.

**Comment by micha12342** [comment]
Yes, that solve our problem. So many thanks, it makes a lot of fun to play ICBM Mod !!! ;)
