### ISSUE TITLE
[1.12] Crash with Dynamic Trees

### ISSUE THREAD

**Issue by UnknownSerhan** [BuiltBrokenModding/ICBM-Classic#419]
Anti Gravitional and Red Matter explosives cause crash with Dynamic Trees mod. When you set them off close to dynamic trees, the game will crash.

Crash Report:
[crash-2023-08-05_12.57.47-client.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/12266788/crash-2023-08-05_12.57.47-client.txt)

**Comment by DarkGuardsman** [comment]
Hmm will have to check but this might actually be a bug in dynamic trees. As we are just calling a vanilla render function.

```
java.lang.NullPointerException: Rendering entity in world
	at com.ferreusveritas.dynamictrees.blocks.LeavesPropertiesJson.lambda$processColor$1(LeavesPropertiesJson.java:285)
	at com.ferreusveritas.dynamictrees.blocks.LeavesPropertiesJson$$Lambda$3860/159683361.func_186720_a(Unknown Source)
	at com.ferreusveritas.dynamictrees.blocks.LeavesPropertiesJson.foliageColorMultiplier(LeavesPropertiesJson.java:271)
	at com.ferreusveritas.dynamictrees.proxy.ClientProxy.lambda$registerColorHandlers$7(ClientProxy.java:226)
	at com.ferreusveritas.dynamictrees.proxy.ClientProxy$$Lambda$3439/1978113165.func_186720_a(Unknown Source)
	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:185)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178266_a(BlockModelRenderer.java:476)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175016_a(BlockRendererDispatcher.java:120)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175016_a(CCBlockRendererDispatcher.java:131)
	at icbm.classic.client.render.entity.RenderEntityBlock.doRender(RenderEntityBlock.java:41)
	at icbm.classic.client.render.entity.RenderEntityBlock.func_76986_a(RenderEntityBlock.java:16)
```
Entity: Entity Name: Flying Block [dynamictrees:leaves0[decayable=true,hydro=1,tree=2], 1934131]

ICBM: ICBM-classic-1.12.2-5.3.0.jar 
dynamic trees: DynamicTrees-1.12.2-0.9.29.jar

**Comment by DarkGuardsman** [comment]
Created: 573dd1535765f4cf8979ddb647df916bb163cee2 which will be released later. It doesn't fix the actual issue but will prevent the game from crashing. Will see log messages client side for any mods with broken renders. Please report this issue to dynamic trees as their color render code is likely broken.
