### ISSUE TITLE
[1.12] v6 - null RadarMap.remove

### ISSUE THREAD

**Issue by xJon** [BuiltBrokenModding/ICBM-Classic#444]
Occurs without having any Radars placed.
```
 [Client thread/WARN]: Attempted to add radar chunk mid access of entities
java.lang.RuntimeException: null
	at icbm.classic.lib.radar.RadarMap.remove(RadarMap.java:190) [RadarMap.class:6.3.1]
	at icbm.classic.lib.radar.RadarRegistry.chunkUnload(RadarRegistry.java:171) [RadarRegistry.class:6.3.1]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_863_RadarRegistry_chunkUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.world.chunk.Chunk.onUnload(Chunk.java:879) [axw.class:?]
	at net.minecraft.client.multiplayer.ChunkProviderClient.unloadChunk(ChunkProviderClient.java:47) [brx.class:?]
	at net.minecraft.client.multiplayer.WorldClient.doPreChunk(WorldClient.java:189) [bsb.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.processChunkUnload(NetHandlerPlayClient.java:768) [brz.class:?]
	at net.minecraft.network.play.server.SPacketUnloadChunk.processPacket(SourceFile:35) [jb.class:?]
	at net.minecraft.network.play.server.SPacketUnloadChunk.processPacket(SourceFile:8) [jb.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(MinecraftMixin.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.run(MinecraftMixin.java:6114) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by DarkGuardsman** [comment]
Did this result in a crash or just console spam?

Its not coming from the radar. Missiles add themselves to the radar map automatically. This is an alert that a chunk loaded while the radar map was updating.

**Comment by xJon** [comment]
Just console spam.

**Comment by DarkGuardsman** [comment]
Note to self: Likely needs same fix as https://github.com/BuiltBrokenModding/ICBM-Classic/issues/452

**Comment by DarkGuardsman** [comment]
Fixed in v6.5.4
