### ISSUE TITLE
[1.12] Dedicated server crash on startup v6.4.0

### ISSUE THREAD

**Issue by josh0x10c** [BuiltBrokenModding/ICBM-Classic#450]
I had attempted to upgrade my modpack server with ICBM version 6.4.0 from 6.3.1 and the server crashes on initialization.
The client will load just fine with no issues though. I removed all other mods and just had ICBM 6.4.0 on a fresh install and the issue still occurs. It appears as if the mod is expecting to be ran on clientside only based on the log. Log file below.

```[00:15:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[00:15:37] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[00:15:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[00:15:37] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[00:15:37] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_422, running on Linux:amd64:6.10.11-200.fc40.x86_64, installed at /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.422.b06-2.fc40.x86_64/jre
[00:15:37] [main/INFO] [FML]: Searching /var/home/robot/Desktop/MC/Asteria/Classica Technica/Server/Classica Technica Server 1.2/./mods for mods
[00:15:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:15:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[00:15:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:15:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:15:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:15:43] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[00:15:43] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:15:43] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[00:15:43] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[00:15:43] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[00:15:43] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[00:15:44] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting minecraft server version 1.12.2
[00:15:44] [Server thread/INFO] [FML]: MinecraftForge v14.23.5.2860 Initialized
[00:15:44] [Server thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[00:15:44] [Server thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[00:15:44] [Server thread/INFO] [FML]: Replaced 1227 ore ingredients
[00:15:44] [Server thread/INFO] [FML]: Searching /var/home/robot/Desktop/MC/Asteria/Classica Technica/Server/Classica Technica Server 1.2/./mods for mods
[00:15:45] [Server thread/WARN] [FML]: Mod icbmclassic is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 6.4.0
[00:15:45] [Server thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[00:15:45] [Server thread/WARN] [FML]: Missing English translation for FML: assets/fml/lang/en_us.lang
[00:15:45] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, icbmclassic] at CLIENT
[00:15:45] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, icbmclassic] at SERVER
[00:15:45] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[00:15:45] [Server thread/INFO] [FML]: Found 1211 ObjectHolder annotations
[00:15:45] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[00:15:45] [Server thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[00:15:45] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[00:15:45] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[00:15:45] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class net.minecraft.entity.EntityAgeable from class icbm.classic.lib.capability.chicken.CapSpaceChicken
[00:15:45] [Server thread/INFO] [icbmclassic]: ExplosiveRegistry: loading registry save, File: /var/home/robot/Desktop/MC/Asteria/Classica Technica/Server/Classica Technica Server 1.2/config/icbmclassic/explosive_reg.json
[00:15:45] [Server thread/INFO] [FML]: Applying holder lookups
[00:15:45] [Server thread/INFO] [FML]: Holder lookups applied
[00:15:45] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@34f7cc63:
java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at icbm.classic.content.reg.ItemReg.registerItems(ItemReg.java:139) ~[ItemReg.class:6.4.0]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_ItemReg_registerItems_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850) [GameData.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_422]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_422]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_422]
	... 12 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@5305c37d from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_422]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_422]
	... 12 more
Caused by: java.lang.RuntimeException: Attempted to load class bud for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_422]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_422]
	... 12 more
[00:15:45] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[00:15:45] [Server thread/ERROR] [FML]: 0: NORMAL
[00:15:45] [Server thread/ERROR] [FML]: 1: net.minecraftforge.fml.common.eventhandler.EventBus$1@1ee91d62
[00:15:45] [Server thread/ERROR] [FML]: 2: net.minecraftforge.fml.common.eventhandler.EventBus$1@18266cc2
[00:15:45] [Server thread/ERROR] [FML]: 3: net.minecraftforge.fml.common.eventhandler.EventBus$1@50783e7d
[00:15:45] [Server thread/ERROR] [FML]: 4: net.minecraftforge.fml.common.eventhandler.EventBus$1@44869f3a
[00:15:45] [Server thread/ERROR] [FML]: 5: net.minecraftforge.fml.common.eventhandler.EventBus$1@125298c5
[00:15:45] [Server thread/ERROR] [FML]: 6: net.minecraftforge.fml.common.eventhandler.EventBus$1@39b9b631
[00:15:45] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at icbm.classic.content.reg.ItemReg.registerItems(ItemReg.java:139) ~[ItemReg.class:6.4.0]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_ItemReg_registerItems_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850) ~[GameData.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_422]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_422]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_422]
	... 12 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@5305c37d from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_422]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_422]
	... 12 more
Caused by: java.lang.RuntimeException: Attempted to load class bud for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_422]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_422]
	... 12 more
[00:15:45] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /var/home/robot/Desktop/MC/Asteria/Classica Technica/Server/Classica Technica Server 1.2/./crash-reports/crash-2024-09-30_00.15.45-server.txt
[00:15:45] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[00:15:45] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[00:15:45] [Server thread/INFO] [FML]: The state engine was in incorrect state INITIALIZATION and forced into state SERVER_STOPPED. Errors may have been discarded.
[00:15:45] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[00:15:45] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds```

**Comment by DarkGuardsman** [comment]
I'll push a build shortly, seems the tooltip code was missing `@SideOnly` check. Previously it never used client side only code so didn't fail. Last release introduced getting contained item tooltip and needed client side player to render properly.

**Comment by DarkGuardsman** [comment]
New version, might take a bit for CF to process https://legacy.curseforge.com/minecraft/mc-mods/icbm/files/5770085
