### ISSUE TITLE
crash using the rocket launcher with homing missile

### ISSUE THREAD

**Issue by erilun06** [BuiltBrokenModding/ICBM-Classic#61]
Encountered an unexpected exception
java.lang.NoSuchMethodError: resonant.api.explosion.ExplosionEvent$ExplosivePreDetonationEvent.<init>(Lnet/minecraft/world/World;DDDLresonant/api/explosion/ExplosiveType;Lcom/builtbroken/mc/api/explosive/IExplosiveHandler;)V
	at icbm.classic.content.items.ItemRocketLauncher.func_77659_a(ItemRocketLauncher.java:73)
	at net.minecraft.item.ItemStack.func_77957_a(Unknown Source)
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(Unknown Source)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by DarkGuardsman** [comment]
Update to the latest alpha of both voltz engine and ICBM classic. The version of voltz engine your using is missing the Resonant Engine API used by classic.
