### ISSUE TITLE
crash when placing explosive block

### ISSUE THREAD

**Issue by erilun06** [BuiltBrokenModding/ICBM-Classic#66]
JourneyMap: Press [J]
13:30:25	net.minecraft.server.MinecraftServer	Server thread	error	Encountered an unexpected exception
java.lang.NoSuchMethodError: resonant.api.explosion.ExplosionEvent$ExplosivePreDetonationEvent.<init>(Lnet/minecraft/world/World;DDDLresonant/api/explosion/ExplosiveType;Lcom/builtbroken/mc/api/explosive/IExplosiveHandler;)V
	at icbm.classic.content.explosive.tile.BlockExplosive.func_149689_a(BlockExplosive.java:149)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:213)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
13:30:25	net.minecraft.server.MinecraftServer	Server thread	error	This crash report has been saved to: C:\Users\elev\Documents\Curse\Minecraft\Instances\resonant test\crash-reports\crash-2017-06-07_13.30.25-server.txt
13:30:25	net.minecraft.server.MinecraftServer	Server thread	info	Stopping server

**Comment by DarkGuardsman** [comment]
Update to the latest alpha of VE and ICBM-Classic. The current beta version is missing the RE api used by the old ICBM-Classic code.

**Comment by erilun06** [comment]
what build is that?
