### ISSUE TITLE
Server crash when using AntiMatter bomb

### ISSUE THREAD

**Issue by Kowantify** [BuiltBrokenModding/ICBM-Classic#88]
https://pastebin.com/uwZMtE4S

Not to sure as to what mod is the issue, it's either ICBM or Minecolonies, I can't really tell, but yeah i lit off a bomb near the colony and boom! it crashed the server side, not client

**Comment by DarkGuardsman** [comment]
``` 
java.lang.NullPointerException: Ticking entity
    at com.minecolonies.coremod.entity.EntityCitizen.getInventoryCitizen(EntityCitizen.java:1580)
    at com.minecolonies.coremod.entity.EntityCitizen.func_82160_b(EntityCitizen.java:1482)
 ```

Base on this I want to say its minecolonies

Especially since all ICBM is doing is calling damage
```
  at com.minecolonies.coremod.entity.EntityCitizen.func_70097_a(EntityCitizen.java:558)
    at icbm.classic.content.explosive.blast.Blast.doDamageEntities(Blast.java:204)
```
